# fly.toml app configuration file generated for pkg-jsn-cam on 2025-05-13T21:01:17-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jsn'
primary_region = 'yyz'

[http_service]
  internal_port = 2143
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'

[[metrics]]
  port = 9091
  path = '/metrics'
  https = false
